version: '3'

services:
  client:
    container_name: starter-react
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./:/app
      - ./node_modules:/app/node_modules
    ports:
      - "3000:3000"
